name: JDK Feature Branch build
run-name: JDK Feature Branch build

on:
  pull_request: 
    branches:
      - main
    paths:
      - 'src/java/**'

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "============="
          echo "=== DEBUG ==="
          echo "============="
          echo "github ref: " ${{ vars.GITHUB_REF }}
          
  feature_branch:
    name: Feature Branch Build
    runs-on: ubuntu-latest
    needs: debug
    
    steps:
      - name: Getting the code
        uses: actions/checkout@v4
        
      - name: Setting up java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'
          cache: 'maven'
          
      - name: Build
        run: |
          mvn clean compile -f src/java/pom.xml
          
      - name: Test
        run: |
          mvn package -f src/java/pom.xml
      
        
        
