name: JDK Main Branch build
run-name: JDK Main Branch build

on:
  push:
    branches:
      - main
    paths:
      - 'src/java/**'

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "============="
          echo "=== DEBUG ==="
          echo "============="
          echo "github ref: " ${{ vars.GITHUB_REF }}
  
  main_branch:
    name: Main Branch Build
    runs-on: ubuntu-latest
    needs: debug
    environment: 
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
      pages: write
      id-token: write
    
    steps:
      - name: Getting the code
        uses: actions/checkout@v4

      - name: Setting up java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'
          cache: 'maven'

      - name: Build
        run: |
          mvn clean compile -f src/java/pom.xml

      - name: Test
        run: |
          mvn package -f src/java/pom.xml
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install Semantic Dependencies
        run: |
          npm install npm
          npm install semantic-release
          npm install @semantic-release/changelog
          npm install @semantic-release/exec
          npm install @semantic-release/git
          npm install @semantic-release/github
          npm install asciidoctor-plantuml

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          cache: 'pip'

      - name: Debug Info Python tools
        run: |
          pip3 --version
          pip3 install --user bump2version

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_SEMANTIC_RELEASE }}
        run: |
          npx semantic-release

#      - run: dotnet tool update -g docfx
#
#      - run: docfx Docs/docfx.json --output Docs/_site
#
#      - name: Setup pages
#        uses: actions/configure-pages@v3
#
#      - name: Upload artifact
#        uses: actions/upload-pages-artifact@v2
#        env:
#          GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_SEMANTIC_RELEASE }}
#        with:
#          path: 'Docs/_site'
#
#      - name: Deploy to Github Pages
#        env:
#          GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_SEMANTIC_RELEASE }}
#        id: deployment
#        uses: actions/deploy-pages@v2
